In [2]:
# Remove Duplicates & Fix Data Types in Pandas

import pandas as pd
import numpy as np

# Sample DataFrame with duplicates and incorrect data types
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Alice', 'Eve'],
    'Age': ['25', '30', '35', '25', '40'],
    'Gender': ['F', 'M', 'M', 'F', 'F'],
    'Score': ['85', '90', '95', '85', '100']
}

df = pd.DataFrame(data)

# Display the original DataFrame
print("Original DataFrame:")
print(df)

# 1. Remove duplicate rows
df_no_duplicates = df.drop_duplicates()
print("\nDataFrame after removing duplicate rows:")
print(df_no_duplicates)

# 2. Fix data types
df_no_duplicates['Age'] = pd.to_numeric(df_no_duplicates['Age'], errors='coerce')
df_no_duplicates['Score'] = pd.to_numeric(df_no_duplicates['Score'], errors='coerce')

print("\nDataFrame after fixing data types:")
print(df_no_duplicates)

# 3. Check data types
print("\nData types of each column:")
print(df_no_duplicates.dtypes)

Original DataFrame:
      Name Age Gender Score
0    Alice  25      F    85
1      Bob  30      M    90
2  Charlie  35      M    95
3    Alice  25      F    85
4      Eve  40      F   100

DataFrame after removing duplicate rows:
      Name Age Gender Score
0    Alice  25      F    85
1      Bob  30      M    90
2  Charlie  35      M    95
4      Eve  40      F   100

DataFrame after fixing data types:
      Name  Age Gender  Score
0    Alice   25      F     85
1      Bob   30      M     90
2  Charlie   35      M     95
4      Eve   40      F    100

Data types of each column:
Name      object
Age        int64
Gender    object
Score      int64
dtype: object

<ipython-input-2-e61ea9cf0053>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_no_duplicates['Age'] = pd.to_numeric(df_no_duplicates['Age'], errors='coerce')
<ipython-input-2-e61ea9cf0053>:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_no_duplicates['Score'] = pd.to_numeric(df_no_duplicates['Score'], errors='coerce')