In [5]:
# Import necessary libraries
import pandas as pd
import numpy as np

# Create a sample DataFrame with missing values
data = {
    'Age': [25, np.nan, 30, np.nan, 29, 27, 32, 31],
    'Fare': [100, 200, np.nan, 150, 120, np.nan, 180, 160],
    'Gender': ['Male', 'Female', np.nan, 'Female', 'Male', 'Male', np.nan, 'Female']
}

df = pd.DataFrame(data)

# Display the original DataFrame
print("Original DataFrame with Missing Values:")
print(df)

# Impute missing values in 'Age' column with mean
df['Age_mean_imputed'] = df['Age'].fillna(df['Age'].mean())

# Impute missing values in 'Fare' column with median
df['Fare_median_imputed'] = df['Fare'].fillna(df['Fare'].median())

# Impute missing values in 'Gender' column with mode
df['Gender_mode_imputed'] = df['Gender'].fillna(df['Gender'].mode()[0])

# Display the DataFrame after imputation
print("\nDataFrame after Imputation:")
print(df)

Original DataFrame with Missing Values:
    Age   Fare  Gender
0  25.0  100.0    Male
1   NaN  200.0  Female
2  30.0    NaN     NaN
3   NaN  150.0  Female
4  29.0  120.0    Male
5  27.0    NaN    Male
6  32.0  180.0     NaN
7  31.0  160.0  Female

DataFrame after Imputation:
    Age   Fare  Gender  Age_mean_imputed  Fare_median_imputed  \
0  25.0  100.0    Male              25.0                100.0
1   NaN  200.0  Female              29.0                200.0
2  30.0    NaN     NaN              30.0                155.0
3   NaN  150.0  Female              29.0                150.0
4  29.0  120.0    Male              29.0                120.0
5  27.0    NaN    Male              27.0                155.0
6  32.0  180.0     NaN              32.0                180.0
7  31.0  160.0  Female              31.0                160.0

  Gender_mode_imputed
0                Male
1              Female
2              Female
3              Female
4                Male
5                Male
6              Female
7              Female